version: '3.7'

services:
  web:
    build: ./web
    container_name: web_app
    command: gunicorn --bind 0.0.0.0:5000 run:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
  nginx_server:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - 80:80
    depends_on:
      - web
