"""add about_me location and name to User model

Revision ID: 3cc68b810d17
Revises: b5401c1eee41
Create Date: 2021-05-03 18:36:28.193891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3cc68b810d17"
down_revision = "b5401c1eee41"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("about_me", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("location", sa.String(length=64), nullable=True))
    op.add_column("users", sa.Column("name", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")
    op.drop_column("users", "location")
    op.drop_column("users", "about_me")

    # ### end Alembic commands ###
