"""add last_seen column in User model

Revision ID: b5401c1eee41
Revises: df7ee228ff05
Create Date: 2021-05-03 17:19:40.413074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b5401c1eee41"
down_revision = "df7ee228ff05"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_seen", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_seen")
    # ### end Alembic commands ###
