"""Add comments

Revision ID: df7ee228ff05
Revises: ff1ba63074a7
Create Date: 2021-03-28 19:45:05.634647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df7ee228ff05"
down_revision = "ff1ba63074a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_comment_timestamp"), "comment", ["timestamp"], unique=False
    )
    op.add_column(
        "users", sa.Column("avatar_hash", sa.String(length=32), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_hash")
    op.drop_index(op.f("ix_comment_timestamp"), table_name="comment")
    op.drop_table("comment")
    # ### end Alembic commands ###
